<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <Deterministic>true</Deterministic>
    <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
    <Company>GameLibrary</Company>
    <Product>GameLibrary</Product>
    <Version>1.4.2</Version>
    <NeutralLanguage>en-US</NeutralLanguage>
  </PropertyGroup>
</Project>
