<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Version>1.1.4</Version>
    <Product>GameLibrary</Product>
    <AssemblyTitle>GameLibrary MCP</AssemblyTitle>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\GameLibrary.HostClient\GameLibrary.HostClient.csproj" />
    <ProjectReference Include="..\GameLibrary.Contracts\GameLibrary.Contracts.csproj" />
  </ItemGroup>

</Project>
