; Interface strings: Simplified Chinese, Traditional Chinese, English, Japanese.
LangString GL_Text0 ${LANG_SIMPCHINESE} "${PRODUCT_NAME} ${VERSION} 安装（界面预览）"
LangString GL_Text0 ${LANG_TRADCHINESE} "${PRODUCT_NAME} ${VERSION} 安裝（介面預覽）"
LangString GL_Text0 ${LANG_ENGLISH} "${PRODUCT_NAME} ${VERSION} Setup (UI preview)"
LangString GL_Text0 ${LANG_JAPANESE} "${PRODUCT_NAME} ${VERSION} セットアップ（画面プレビュー）"
LangString GL_Text1 ${LANG_SIMPCHINESE} "${PRODUCT_NAME} ${VERSION} 安装"
LangString GL_Text1 ${LANG_TRADCHINESE} "${PRODUCT_NAME} ${VERSION} 安裝"
LangString GL_Text1 ${LANG_ENGLISH} "${PRODUCT_NAME} ${VERSION} Setup"
LangString GL_Text1 ${LANG_JAPANESE} "${PRODUCT_NAME} ${VERSION} セットアップ"
LangString GL_Text2 ${LANG_SIMPCHINESE} "GameLibrary · MIT 开源"
LangString GL_Text2 ${LANG_TRADCHINESE} "GameLibrary · MIT 開源"
LangString GL_Text2 ${LANG_ENGLISH} "GameLibrary · MIT open source"
LangString GL_Text2 ${LANG_JAPANESE} "GameLibrary · MIT オープンソース"
LangString GL_Text3 ${LANG_SIMPCHINESE} "${PRODUCT_NAME} 安装程序"
LangString GL_Text3 ${LANG_TRADCHINESE} "${PRODUCT_NAME} 安裝程式"
LangString GL_Text3 ${LANG_ENGLISH} "${PRODUCT_NAME} Setup"
LangString GL_Text3 ${LANG_JAPANESE} "${PRODUCT_NAME} セットアップ"
LangString GL_Text4 ${LANG_SIMPCHINESE} "界面预览完成"
LangString GL_Text4 ${LANG_TRADCHINESE} "介面預覽完成"
LangString GL_Text4 ${LANG_ENGLISH} "UI preview complete"
LangString GL_Text4 ${LANG_JAPANESE} "画面プレビュー完了"
LangString GL_Text5 ${LANG_SIMPCHINESE} "界面预览已完成。$\r$\n$\r$\n此预览没有安装程序、创建快捷方式或修改卸载登记。"
LangString GL_Text5 ${LANG_TRADCHINESE} "介面預覽已完成。$\r$\n$\r$\n此預覽沒有安裝程式、創建捷徑或修改卸載登記。"
LangString GL_Text5 ${LANG_ENGLISH} "UI preview complete.$\r$\n$\r$\nNo program was installed, no shortcuts were created, and no uninstall registration was changed."
LangString GL_Text5 ${LANG_JAPANESE} "画面プレビューが完了しました。$\r$\n$\r$\nインストール、ショートカットの作成、アンインストール登録の変更は行っていません。"
LangString GL_Text6 ${LANG_SIMPCHINESE} "${PRODUCT_NAME} 安装完成"
LangString GL_Text6 ${LANG_TRADCHINESE} "${PRODUCT_NAME} 安裝完成"
LangString GL_Text6 ${LANG_ENGLISH} "${PRODUCT_NAME} installed"
LangString GL_Text6 ${LANG_JAPANESE} "${PRODUCT_NAME} のインストールが完了しました"
LangString GL_Text7 ${LANG_SIMPCHINESE} "启动 ${PRODUCT_NAME}"
LangString GL_Text7 ${LANG_TRADCHINESE} "啟動 ${PRODUCT_NAME}"
LangString GL_Text7 ${LANG_ENGLISH} "Launch ${PRODUCT_NAME}"
LangString GL_Text7 ${LANG_JAPANESE} "${PRODUCT_NAME} を起動"
LangString GL_Text8 ${LANG_SIMPCHINESE} "查看项目主页"
LangString GL_Text8 ${LANG_TRADCHINESE} "查看項目主頁"
LangString GL_Text8 ${LANG_ENGLISH} "View project website"
LangString GL_Text8 ${LANG_JAPANESE} "プロジェクトのページを開く"
LangString GL_Text9 ${LANG_SIMPCHINESE} "许可协议"
LangString GL_Text9 ${LANG_TRADCHINESE} "許可協議"
LangString GL_Text9 ${LANG_ENGLISH} "License agreement"
LangString GL_Text9 ${LANG_JAPANESE} "ライセンス契約"
LangString GL_Text10 ${LANG_SIMPCHINESE} "请阅读 ${PRODUCT_NAME} 的 MIT 开源许可。"
LangString GL_Text10 ${LANG_TRADCHINESE} "請閱讀 ${PRODUCT_NAME} 的 MIT 開源許可。"
LangString GL_Text10 ${LANG_ENGLISH} "Read the MIT license for ${PRODUCT_NAME}."
LangString GL_Text10 ${LANG_JAPANESE} "${PRODUCT_NAME} の MIT ライセンスをお読みください。"
LangString GL_Text11 ${LANG_SIMPCHINESE} "请阅读以下许可条款。"
LangString GL_Text11 ${LANG_TRADCHINESE} "請閱讀以下許可條款。"
LangString GL_Text11 ${LANG_ENGLISH} "Please read the following license terms."
LangString GL_Text11 ${LANG_JAPANESE} "次のライセンス条項をお読みください。"
LangString GL_Text12 ${LANG_SIMPCHINESE} "我同意此许可协议(&A)"
LangString GL_Text12 ${LANG_TRADCHINESE} "我同意此許可協議(&A)"
LangString GL_Text12 ${LANG_ENGLISH} "I &accept the license agreement"
LangString GL_Text12 ${LANG_JAPANESE} "ライセンスに同意する(&A)"
LangString GL_Text13 ${LANG_SIMPCHINESE} "我不同意此许可协议(&D)"
LangString GL_Text13 ${LANG_TRADCHINESE} "我不同意此許可協議(&D)"
LangString GL_Text13 ${LANG_ENGLISH} "I &do not accept the license agreement"
LangString GL_Text13 ${LANG_JAPANESE} "ライセンスに同意しない(&D)"
LangString GL_Text14 ${LANG_SIMPCHINESE} "选择安装位置"
LangString GL_Text14 ${LANG_TRADCHINESE} "選擇安裝位置"
LangString GL_Text14 ${LANG_ENGLISH} "Choose install location"
LangString GL_Text14 ${LANG_JAPANESE} "インストール先を選択"
LangString GL_Text15 ${LANG_SIMPCHINESE} "将 ${PRODUCT_NAME} 安装到哪个文件夹？"
LangString GL_Text15 ${LANG_TRADCHINESE} "將 ${PRODUCT_NAME} 安裝到哪個資料夾？"
LangString GL_Text15 ${LANG_ENGLISH} "Where should ${PRODUCT_NAME} be installed?"
LangString GL_Text15 ${LANG_JAPANESE} "${PRODUCT_NAME} のインストール先を選択してください。"
LangString GL_Text16 ${LANG_SIMPCHINESE} "程序将安装到下方文件夹。若要修改位置，请点击“浏览”。$\r$\n游戏库数据单独保存在用户数据目录，卸载时会保留。"
LangString GL_Text16 ${LANG_TRADCHINESE} "程式將安裝到下方資料夾。若要修改位置，請點擊“瀏覽”。$\r$\n游戲庫資料單獨保存在用戶資料目錄，卸載時會保留。"
LangString GL_Text16 ${LANG_ENGLISH} "The program will be installed in the folder below. Click Browse to change it.$\r$\nLibrary data is stored separately and kept when uninstalling."
LangString GL_Text16 ${LANG_JAPANESE} "次のフォルダーにインストールします。変更するには「参照」を選択してください。$\r$\nライブラリのデータは別の場所に保存され、アンインストール時にも保持されます。"
LangString GL_Text17 ${LANG_SIMPCHINESE} "欢迎安装 ${PRODUCT_NAME}"
LangString GL_Text17 ${LANG_TRADCHINESE} "歡迎安裝 ${PRODUCT_NAME}"
LangString GL_Text17 ${LANG_ENGLISH} "Welcome to ${PRODUCT_NAME} Setup"
LangString GL_Text17 ${LANG_JAPANESE} "${PRODUCT_NAME} セットアップへようこそ"
LangString GL_Text18 ${LANG_SIMPCHINESE} "安装向导将引导你完成以下步骤。"
LangString GL_Text18 ${LANG_TRADCHINESE} "安裝向導將引導你完成以下步驟。"
LangString GL_Text18 ${LANG_ENGLISH} "This wizard will guide you through setup."
LangString GL_Text18 ${LANG_JAPANESE} "このウィザードでインストールを行います。"
LangString GL_Text19 ${LANG_SIMPCHINESE} "本程序用于整理和启动本地游戏。$\r$\n你可以在安装前查看许可条款并选择安装位置。"
LangString GL_Text19 ${LANG_TRADCHINESE} "本程式用于整理和啟動本地游戲。$\r$\n你可以在安裝前查看許可條款并選擇安裝位置。"
LangString GL_Text19 ${LANG_ENGLISH} "Organize and launch your local games.$\r$\nReview the license and choose an install location before installing."
LangString GL_Text19 ${LANG_JAPANESE} "ローカルのゲームを整理して起動するアプリです。$\r$\nライセンスを確認し、インストール先を選択できます。"
LangString GL_Text20 ${LANG_SIMPCHINESE} "仅为当前 Windows 用户安装，无需管理员权限。$\r$\n游戏文件留在原处，游戏库数据单独保存。"
LangString GL_Text20 ${LANG_TRADCHINESE} "僅為當前 Windows 用戶安裝，無需管理員權限。$\r$\n游戲檔案留在原處，游戲庫資料單獨保存。"
LangString GL_Text20 ${LANG_ENGLISH} "Installed for the current Windows user; no administrator rights needed.$\r$\nGame files stay in place. Library data is stored separately."
LangString GL_Text20 ${LANG_JAPANESE} "現在の Windows ユーザー用にインストールします。管理者権限は不要です。$\r$\nゲームファイルは移動せず、ライブラリのデータは別に保存します。"
LangString GL_Text21 ${LANG_SIMPCHINESE} "1.5.4（示例）"
LangString GL_Text21 ${LANG_TRADCHINESE} "1.5.4（示例）"
LangString GL_Text21 ${LANG_ENGLISH} "1.5.4 (example)"
LangString GL_Text21 ${LANG_JAPANESE} "1.5.4（サンプル）"
LangString GL_Text22 ${LANG_SIMPCHINESE} "已安装 ${PRODUCT_NAME}"
LangString GL_Text22 ${LANG_TRADCHINESE} "已安裝 ${PRODUCT_NAME}"
LangString GL_Text22 ${LANG_ENGLISH} "${PRODUCT_NAME} is already installed"
LangString GL_Text22 ${LANG_JAPANESE} "${PRODUCT_NAME} はインストール済みです"
LangString GL_Text23 ${LANG_SIMPCHINESE} "请选择如何处理现有版本。"
LangString GL_Text23 ${LANG_TRADCHINESE} "請選擇如何處理現有版本。"
LangString GL_Text23 ${LANG_ENGLISH} "Choose how to handle the existing version."
LangString GL_Text23 ${LANG_JAPANESE} "既存のバージョンの処理方法を選択してください。"
LangString GL_Text24 ${LANG_SIMPCHINESE} "检测到已安装的版本：$PreviousVersion$\r$\n建议先卸载旧版程序，再安装新版本。"
LangString GL_Text24 ${LANG_TRADCHINESE} "檢測到已安裝的版本：$PreviousVersion$\r$\n建議先卸載舊版程式，再安裝新版本。"
LangString GL_Text24 ${LANG_ENGLISH} "Installed version: $PreviousVersion$\r$\nUninstalling the old version first is recommended."
LangString GL_Text24 ${LANG_JAPANESE} "既存のバージョン：$PreviousVersion$\r$\n旧バージョンをアンインストールしてからの更新を推奨します。"
LangString GL_Text25 ${LANG_SIMPCHINESE} "先卸载旧版再安装（推荐）(&U)"
LangString GL_Text25 ${LANG_TRADCHINESE} "先卸載舊版再安裝（推薦）(&U)"
LangString GL_Text25 ${LANG_ENGLISH} "&Uninstall the old version first (recommended)"
LangString GL_Text25 ${LANG_JAPANESE} "旧バージョンをアンインストールする（推奨）(&U)"
LangString GL_Text26 ${LANG_SIMPCHINESE} "保留旧版文件，直接覆盖安装(&K)"
LangString GL_Text26 ${LANG_TRADCHINESE} "保留舊版檔案，直接覆蓋安裝(&K)"
LangString GL_Text26 ${LANG_ENGLISH} "&Keep old files and install over them"
LangString GL_Text26 ${LANG_JAPANESE} "旧ファイルを保持して上書きする(&K)"
LangString GL_Text27 ${LANG_SIMPCHINESE} "卸载只清理程序文件，保留游戏库数据。$\r$\n选择覆盖安装可能留下旧版文件。"
LangString GL_Text27 ${LANG_TRADCHINESE} "卸載只清理程式檔案，保留游戲庫資料。$\r$\n選擇覆蓋安裝可能留下舊版檔案。"
LangString GL_Text27 ${LANG_ENGLISH} "Uninstalling removes program files only; library data is kept.$\r$\nInstalling over the old version may leave old files behind."
LangString GL_Text27 ${LANG_JAPANESE} "アンインストールではプログラムファイルのみを削除し、データは保持します。$\r$\n上書きの場合、旧ファイルが残ることがあります。"
LangString GL_Text28 ${LANG_SIMPCHINESE} "准备安装"
LangString GL_Text28 ${LANG_TRADCHINESE} "準備安裝"
LangString GL_Text28 ${LANG_ENGLISH} "Ready to install"
LangString GL_Text28 ${LANG_JAPANESE} "インストールの準備完了"
LangString GL_Text29 ${LANG_SIMPCHINESE} "请确认以下设置，然后点击“安装”。"
LangString GL_Text29 ${LANG_TRADCHINESE} "請確認以下設定，然后點擊“安裝”。"
LangString GL_Text29 ${LANG_ENGLISH} "Review the settings below, then click Install."
LangString GL_Text29 ${LANG_JAPANESE} "設定を確認し、「インストール」を押してください。"
LangString GL_Text30 ${LANG_SIMPCHINESE} "新安装"
LangString GL_Text30 ${LANG_TRADCHINESE} "新安裝"
LangString GL_Text30 ${LANG_ENGLISH} "New installation"
LangString GL_Text30 ${LANG_JAPANESE} "新規インストール"
LangString GL_Text31 ${LANG_SIMPCHINESE} "先卸载旧版，再安装新版本"
LangString GL_Text31 ${LANG_TRADCHINESE} "先卸載舊版，再安裝新版本"
LangString GL_Text31 ${LANG_ENGLISH} "Uninstall the old version, then install the new version"
LangString GL_Text31 ${LANG_JAPANESE} "旧バージョンを削除してから新バージョンをインストール"
LangString GL_Text32 ${LANG_SIMPCHINESE} "保留旧版文件，直接覆盖安装"
LangString GL_Text32 ${LANG_TRADCHINESE} "保留舊版檔案，直接覆蓋安裝"
LangString GL_Text32 ${LANG_ENGLISH} "Keep old files and install over them"
LangString GL_Text32 ${LANG_JAPANESE} "旧ファイルを保持して上書き"
LangString GL_Text33 ${LANG_SIMPCHINESE} "目标位置：$\r$\n  $INSTDIR$\r$\n$\r$\n安装范围：当前 Windows 用户$\r$\n安装方式：$1$\r$\n$\r$\n快捷方式：$\r$\n  开始菜单中的 ${PRODUCT_NAME} 和卸载入口"
LangString GL_Text33 ${LANG_TRADCHINESE} "目標位置：$\r$\n  $INSTDIR$\r$\n$\r$\n安裝范圍：當前 Windows 用戶$\r$\n安裝方式：$1$\r$\n$\r$\n捷徑：$\r$\n  開始菜單中的 ${PRODUCT_NAME} 和卸載入口"
LangString GL_Text33 ${LANG_ENGLISH} "Destination:$\r$\n  $INSTDIR$\r$\n$\r$\nScope: current Windows user$\r$\nMethod: $1$\r$\n$\r$\nShortcuts:$\r$\n  ${PRODUCT_NAME} and Uninstall in the Start menu"
LangString GL_Text33 ${LANG_JAPANESE} "インストール先：$\r$\n  $INSTDIR$\r$\n$\r$\n対象：現在の Windows ユーザー$\r$\n方法：$1$\r$\n$\r$\nショートカット：$\r$\n  スタートメニューに ${PRODUCT_NAME} とアンインストール"
LangString GL_Text34 ${LANG_SIMPCHINESE} "游戏库数据和游戏文件不会因安装或升级而删除。"
LangString GL_Text34 ${LANG_TRADCHINESE} "游戲庫資料和游戲檔案不會因安裝或升級而刪除。"
LangString GL_Text34 ${LANG_ENGLISH} "Installation and upgrades do not delete library data or game files."
LangString GL_Text34 ${LANG_JAPANESE} "インストールや更新でライブラリのデータやゲームファイルは削除しません。"
LangString GL_Text35 ${LANG_SIMPCHINESE} "安装(&I)"
LangString GL_Text35 ${LANG_TRADCHINESE} "安裝(&I)"
LangString GL_Text35 ${LANG_ENGLISH} "&Install"
LangString GL_Text35 ${LANG_JAPANESE} "インストール(&I)"
LangString GL_Text36 ${LANG_SIMPCHINESE} "仅预览安装向导；没有复制程序或修改安装登记。"
LangString GL_Text36 ${LANG_TRADCHINESE} "僅預覽安裝向導；沒有復制程式或修改安裝登記。"
LangString GL_Text36 ${LANG_ENGLISH} "Setup UI preview only; no files copied or registration changed."
LangString GL_Text36 ${LANG_JAPANESE} "画面のプレビューのみです。ファイルのコピーや登録の変更は行いません。"
LangString GL_Text37 ${LANG_SIMPCHINESE} "正在卸载旧版 ${PRODUCT_NAME}（目录：$PreviousLocation）..."
LangString GL_Text37 ${LANG_TRADCHINESE} "正在卸載舊版 ${PRODUCT_NAME}（目錄：$PreviousLocation）..."
LangString GL_Text37 ${LANG_ENGLISH} "Uninstalling old ${PRODUCT_NAME} (folder: $PreviousLocation)..."
LangString GL_Text37 ${LANG_JAPANESE} "旧 ${PRODUCT_NAME} をアンインストール中（$PreviousLocation）..."
LangString GL_Text38 ${LANG_SIMPCHINESE} "卸载旧版 ${PRODUCT_NAME} 失败（退出码 $R3），安装已中止。$\r$\n请关闭正在运行的 ${PRODUCT_NAME} 后重新运行安装程序。"
LangString GL_Text38 ${LANG_TRADCHINESE} "卸載舊版 ${PRODUCT_NAME} 失敗（退出碼 $R3），安裝已中止。$\r$\n請關閉正在運行的 ${PRODUCT_NAME} 后重新運行安裝程式。"
LangString GL_Text38 ${LANG_ENGLISH} "Could not uninstall old ${PRODUCT_NAME} (exit code $R3). Setup stopped.$\r$\nClose ${PRODUCT_NAME} and run setup again."
LangString GL_Text38 ${LANG_JAPANESE} "旧 ${PRODUCT_NAME} を削除できません（終了コード $R3）。インストールを中止しました。$\r$\n${PRODUCT_NAME} を閉じて再試行してください。"
LangString GL_Text39 ${LANG_SIMPCHINESE} "按用户选择保留旧版文件，直接覆盖安装"
LangString GL_Text39 ${LANG_TRADCHINESE} "按用戶選擇保留舊版檔案，直接覆蓋安裝"
LangString GL_Text39 ${LANG_ENGLISH} "Keeping old files and installing over them as selected"
LangString GL_Text39 ${LANG_JAPANESE} "選択に従い、旧ファイルを保持して上書きします"
LangString GL_Text40 ${LANG_SIMPCHINESE} "本地优先的 Windows 游戏库管理器"
LangString GL_Text40 ${LANG_TRADCHINESE} "本地優先的 Windows 游戲庫管理器"
LangString GL_Text40 ${LANG_ENGLISH} "Local-first Windows game library manager"
LangString GL_Text40 ${LANG_JAPANESE} "ローカル中心の Windows ゲームライブラリ管理アプリ"
LangString GL_Text41 ${LANG_SIMPCHINESE} "卸载 ${PRODUCT_NAME}"
LangString GL_Text41 ${LANG_TRADCHINESE} "卸載 ${PRODUCT_NAME}"
LangString GL_Text41 ${LANG_ENGLISH} "Uninstall ${PRODUCT_NAME}"
LangString GL_Text41 ${LANG_JAPANESE} "${PRODUCT_NAME} をアンインストール"
