"""Generate operation constants, availability, compact schemas and ordinary CLI/MCP mappings."""
import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
HEADER = "// <auto-generated />\n#nullable enable\n// Run: py -3 scripts/generate_operations.py\n"


def quote(value):
    return json.dumps(value, ensure_ascii=False)


def identifier(operation):
    return "".join(part.title() for part in re.split(r"[._]", operation))


def generate(catalog):
    operations = catalog["operations"]
    available = [op for op in operations if op.get("available")]
    constants = [f"    public const string {identifier(op['operationId'])} = {quote(op['operationId'])};"
                 for op in operations]
    contracts = HEADER + "namespace GameLibrary.Contracts;\n\npublic static class OperationIds\n{\n"
    contracts += "\n".join(constants) + "\n}\n\ninternal static class GeneratedOperations\n{\n"
    contracts += "    internal static readonly IReadOnlySet<string> Available = new HashSet<string>(StringComparer.Ordinal)\n    {\n"
    contracts += "".join(f"        OperationIds.{identifier(op['operationId'])},\n" for op in available)
    contracts += "    };\n\n    internal static readonly IReadOnlyDictionary<string, ParamSpec[]> InputSpecs =\n        new Dictionary<string, ParamSpec[]>(StringComparer.Ordinal)\n        {\n"
    for op in operations:
        if "parameters" not in op:
            continue
        specs = ", ".join(f"new({quote(p['name'])}, {quote(p['type'])}, {str(p['required']).lower()}, {quote(p['description'])}, {str(p.get('nullable', False)).lower()})"
                          for p in op["parameters"])
        contracts += f"            [OperationIds.{identifier(op['operationId'])}] = [{specs}],\n"
    contracts += "        };\n}\n"

    cli = HEADER + "using GameLibrary.Contracts;\n\nnamespace GameLibrary.Cli;\n\ninternal static class GeneratedCommandMap\n{\n"
    cli += "    public static string? Resolve(string noun, string verb) => (noun, verb) switch\n    {\n"
    for op in operations:
        if op.get("available") or op["operationId"] == "host.start":
            noun, verb = op["cli"]
            cli += f"        ({quote(noun)}, {quote(verb)}) => OperationIds.{identifier(op['operationId'])},\n"
    cli += "        _ => null,\n    };\n}\n"

    mcp = HEADER + "using System.ComponentModel;\nusing System.Text.Json;\nusing GameLibrary.Contracts;\nusing ModelContextProtocol.Protocol;\nusing ModelContextProtocol.Server;\n\nnamespace GameLibrary.Mcp;\n\npublic static partial class GameLibraryTools\n{\n"
    for op in available:
        forward = op.get("mcpForward")
        if not forward:
            continue
        parameters = []
        specs = sorted(op["parameters"], key=lambda p: not p["required"])
        types = {"string": "string", "integer": "int", "number": "double", "boolean": "bool", "array": "JsonElement"}
        for param in specs:
            clr_type = param.get("csharpType", types[param["type"]])
            optional = not param["required"]
            if optional and clr_type != "JsonElement":
                clr_type += "?"
            default = " = default" if optional and clr_type == "JsonElement" else " = null" if optional else ""
            # AIJsonUtilities otherwise serializes the Undefined struct while deriving a schema.
            # A null metadata default binds to default(JsonElement), preserving omitted vs JSON null.
            metadata_default = "[DefaultValue(null)] " if optional and clr_type == "JsonElement" else ""
            parameters.append(f"{metadata_default}[Description({quote(param['description'])})] {clr_type} {param['name']}{default}")
        args = ", ".join(f"[{quote(p['name'])}] = {p['name']}" for p in specs)
        mcp += f"    [McpServerTool(Name = {quote(op['mcpTool'])})]\n    [Description({quote(forward['description'])})]\n"
        mcp += f"    public static Task<CallToolResult> {forward['method']}({', '.join(parameters)}) =>\n"
        mcp += f"        InvokeGeneratedOperationAsync(OperationIds.{identifier(op['operationId'])}, new Dictionary<string, object?> {{ {args} }});\n\n"
    mcp = mcp.rstrip() + "\n}\n"
    return {
        "src/GameLibrary.Contracts/GeneratedOperations.cs": contracts,
        "src/GameLibrary.Cli/GeneratedCommandMap.cs": cli,
        "src/GameLibrary.Mcp/GameLibraryTools.Generated.cs": mcp,
    }


def validate(catalog, generated):
    operations = catalog["operations"]
    ids = [op["operationId"] for op in operations]
    if len(ids) != len(set(ids)):
        raise ValueError("Duplicate operation ID")
    for op in operations:
        if op.get("mcpForward") and "parameters" in op["mcpForward"]:
            raise ValueError(f"MCP parameters must use the canonical source: {op['operationId']}")
    available = {op["operationId"] for op in operations if op.get("available")}
    host = (ROOT / "src/GameLibrary.Host/Hosting/OperationDispatcher.cs").read_text(encoding="utf-8-sig")
    routes = set()
    for case in re.findall(r'((?:"[a-z_.]+"\s*(?:or\s*)?)+)=>', host):
        routes.update(re.findall(r'"([a-z_.]+)"', case))
    routes.update(re.findall(r'request.OperationId == "([a-z_.]+)"', host))
    for case in re.findall(r'request.OperationId is ((?:"[a-z_.]+"\s*(?:or\s*)?)+)', host):
        routes.update(re.findall(r'"([a-z_.]+)"', case))
    missing = available - routes
    extra = (routes & set(ids)) - available
    if missing or extra:
        raise ValueError(f"Host/catalog mismatch: missing={sorted(missing)}, extra={sorted(extra)}")
    hand_mcp = (ROOT / "src/GameLibrary.Mcp/GameLibraryTools.cs").read_text(encoding="utf-8-sig")
    mcp = hand_mcp + generated["src/GameLibrary.Mcp/GameLibraryTools.Generated.cs"]
    names = re.findall(r'McpServerTool\(Name = "([^"]+)"', mcp)
    expected = {op["mcpTool"] for op in operations if op.get("available")}
    if len(names) != len(set(names)) or set(names) != expected:
        raise ValueError(f"MCP/catalog mismatch: missing={sorted(expected - set(names))}, extra={sorted(set(names) - expected)}")
    cli = (ROOT / "src/GameLibrary.Cli/Program.cs").read_text(encoding="utf-8-sig")
    for operation in available:
        if quote(operation) not in cli and operation not in ("events.wait", "backups.restore_start"):
            raise ValueError(f"Missing CLI forwarding or parameter mapping: {operation}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    catalog = json.loads((ROOT / "contracts/operations.v1.json").read_text(encoding="utf-8-sig"))
    generated = generate(catalog)
    validate(catalog, generated)
    stale = []
    for relative, content in generated.items():
        path = ROOT / relative
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8-sig") != content:
                stale.append(relative)
        else:
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        raise SystemExit("Generated files are stale: " + ", ".join(stale))
    print(f"Operations verified: {sum(op.get('available', False) for op in catalog['operations'])}; generated files: {len(generated)}")


if __name__ == "__main__":
    main()
