// <auto-generated />
#nullable enable
// Run: py -3 scripts/generate_operations.py
namespace GameLibrary.Contracts;

public static class OperationIds
{
    public const string ProfilesDiscover = "profiles.discover";
    public const string TitlesTranslate = "titles.translate";
    public const string TitlesSetDisplay = "titles.set_display";
    public const string TitlesSetTranslated = "titles.set_translated";
    public const string ProfilesRestore = "profiles.restore";
    public const string CapabilitiesGet = "capabilities.get";
    public const string SchemaGet = "schema.get";
    public const string HostStatus = "host.status";
    public const string HostStart = "host.start";
    public const string HostStop = "host.stop";
    public const string LibraryInit = "library.init";
    public const string LibraryStatus = "library.status";
    public const string LibraryExport = "library.export";
    public const string LibraryImportPlan = "library.import_plan";
    public const string LibraryImport = "library.import";
    public const string RootsList = "roots.list";
    public const string RootsGet = "roots.get";
    public const string RootsAdd = "roots.add";
    public const string RootsUpdate = "roots.update";
    public const string RootsRemove = "roots.remove";
    public const string RootsRebind = "roots.rebind";
    public const string RulesList = "rules.list";
    public const string RulesGet = "rules.get";
    public const string RulesCreate = "rules.create";
    public const string RulesUpdate = "rules.update";
    public const string RulesRemove = "rules.remove";
    public const string RulesPreview = "rules.preview";
    public const string ScanStart = "scan.start";
    public const string ScanStatus = "scan.status";
    public const string ScanPause = "scan.pause";
    public const string ScanResume = "scan.resume";
    public const string ScanCancel = "scan.cancel";
    public const string ScanCoverage = "scan.coverage";
    public const string ScanInspect = "scan.inspect";
    public const string CandidatesList = "candidates.list";
    public const string CandidatesGet = "candidates.get";
    public const string CandidatesAccept = "candidates.accept";
    public const string CandidatesDefer = "candidates.defer";
    public const string CandidatesIgnore = "candidates.ignore";
    public const string IgnoresList = "ignores.list";
    public const string IgnoresGet = "ignores.get";
    public const string IgnoresCreate = "ignores.create";
    public const string IgnoresUpdate = "ignores.update";
    public const string IgnoresRemove = "ignores.remove";
    public const string GamesList = "games.list";
    public const string GamesGet = "games.get";
    public const string GamesCreate = "games.create";
    public const string GamesUpdate = "games.update";
    public const string GamesRemove = "games.remove";
    public const string GamesRelink = "games.relink";
    public const string FieldsSet = "fields.set";
    public const string FieldsClear = "fields.clear";
    public const string FieldsReset = "fields.reset";
    public const string TagsList = "tags.list";
    public const string TagsCreate = "tags.create";
    public const string TagsUpdate = "tags.update";
    public const string TagsRemove = "tags.remove";
    public const string TagsAssign = "tags.assign";
    public const string TagsUnassign = "tags.unassign";
    public const string TagsSuppress = "tags.suppress";
    public const string TagsReset = "tags.reset";
    public const string MetadataPreview = "metadata.preview";
    public const string MetadataRefresh = "metadata.refresh";
    public const string AssetsList = "assets.list";
    public const string AssetsGet = "assets.get";
    public const string AssetsImport = "assets.import";
    public const string AssetsChoose = "assets.choose";
    public const string AssetsCrop = "assets.crop";
    public const string AssetsReset = "assets.reset";
    public const string AssetsRemove = "assets.remove";
    public const string ProfilesList = "profiles.list";
    public const string ProfilesGet = "profiles.get";
    public const string ProfilesCreate = "profiles.create";
    public const string ProfilesUpdate = "profiles.update";
    public const string ProfilesRemove = "profiles.remove";
    public const string ProfilesSetDefault = "profiles.set_default";
    public const string ProfilesValidate = "profiles.validate";
    public const string TranslationGet = "translation.get";
    public const string TranslationSet = "translation.set";
    public const string ToolsList = "tools.list";
    public const string ToolsGet = "tools.get";
    public const string ToolsDiscover = "tools.discover";
    public const string ToolsRegister = "tools.register";
    public const string ToolsUpdate = "tools.update";
    public const string ToolsRemove = "tools.remove";
    public const string ToolsCapabilities = "tools.capabilities";
    public const string VerificationStart = "verification.start";
    public const string VerificationGet = "verification.get";
    public const string VerificationList = "verification.list";
    public const string VerificationReport = "verification.report";
    public const string VerificationInvalidate = "verification.invalidate";
    public const string LaunchPlan = "launch.plan";
    public const string LaunchExecute = "launch.execute";
    public const string LaunchStatus = "launch.status";
    public const string LaunchHistory = "launch.history";
    public const string JobsList = "jobs.list";
    public const string JobsGet = "jobs.get";
    public const string JobsWait = "jobs.wait";
    public const string JobsCancel = "jobs.cancel";
    public const string EventsRead = "events.read";
    public const string NotificationsList = "notifications.list";
    public const string NotificationsGet = "notifications.get";
    public const string NotificationsAcknowledge = "notifications.acknowledge";
    public const string NotificationsDefer = "notifications.defer";
    public const string SettingsGet = "settings.get";
    public const string SettingsUpdate = "settings.update";
    public const string SettingsReset = "settings.reset";
    public const string ViewsList = "views.list";
    public const string ViewsGet = "views.get";
    public const string ViewsCreate = "views.create";
    public const string ViewsUpdate = "views.update";
    public const string ViewsRemove = "views.remove";
    public const string ViewsActivate = "views.activate";
    public const string DesktopState = "desktop.state";
    public const string DesktopShow = "desktop.show";
    public const string DesktopNavigate = "desktop.navigate";
    public const string DesktopHide = "desktop.hide";
    public const string DesktopClose = "desktop.close";
    public const string BackupsList = "backups.list";
    public const string BackupsCreate = "backups.create";
    public const string BackupsInspect = "backups.inspect";
    public const string BackupsRestorePlan = "backups.restore_plan";
    public const string BackupsRestore = "backups.restore";
    public const string DiagnosticsStatus = "diagnostics.status";
    public const string DiagnosticsLogs = "diagnostics.logs";
    public const string DiagnosticsExport = "diagnostics.export";
    public const string DiagnosticsCacheRebuild = "diagnostics.cache_rebuild";
    public const string AccessStatus = "access.status";
    public const string AccessList = "access.list";
    public const string AccessConfigure = "access.configure";
    public const string AccessRevoke = "access.revoke";
    public const string ActionsList = "actions.list";
    public const string ActionsGet = "actions.get";
    public const string ActionsComplete = "actions.complete";
    public const string EventsWait = "events.wait";
    public const string BackupsRestoreStart = "backups.restore_start";
    public const string CandidatesReviewBatch = "candidates.review_batch";
    public const string TagsReorder = "tags.reorder";
}

internal static class GeneratedOperations
{
    internal static readonly IReadOnlySet<string> Available = new HashSet<string>(StringComparer.Ordinal)
    {
        OperationIds.ProfilesDiscover,
        OperationIds.TitlesTranslate,
        OperationIds.TitlesSetDisplay,
        OperationIds.TitlesSetTranslated,
        OperationIds.ProfilesRestore,
        OperationIds.CapabilitiesGet,
        OperationIds.SchemaGet,
        OperationIds.HostStatus,
        OperationIds.HostStop,
        OperationIds.LibraryInit,
        OperationIds.RootsList,
        OperationIds.RootsAdd,
        OperationIds.RootsRemove,
        OperationIds.ScanStart,
        OperationIds.ScanStatus,
        OperationIds.ScanCancel,
        OperationIds.ScanCoverage,
        OperationIds.ScanInspect,
        OperationIds.CandidatesList,
        OperationIds.CandidatesGet,
        OperationIds.CandidatesAccept,
        OperationIds.CandidatesDefer,
        OperationIds.CandidatesIgnore,
        OperationIds.IgnoresList,
        OperationIds.IgnoresCreate,
        OperationIds.IgnoresRemove,
        OperationIds.GamesList,
        OperationIds.GamesGet,
        OperationIds.GamesCreate,
        OperationIds.GamesUpdate,
        OperationIds.GamesRemove,
        OperationIds.GamesRelink,
        OperationIds.FieldsSet,
        OperationIds.FieldsClear,
        OperationIds.FieldsReset,
        OperationIds.TagsList,
        OperationIds.TagsCreate,
        OperationIds.TagsUpdate,
        OperationIds.TagsRemove,
        OperationIds.TagsAssign,
        OperationIds.TagsUnassign,
        OperationIds.TagsSuppress,
        OperationIds.TagsReset,
        OperationIds.MetadataPreview,
        OperationIds.MetadataRefresh,
        OperationIds.AssetsList,
        OperationIds.AssetsGet,
        OperationIds.AssetsImport,
        OperationIds.AssetsChoose,
        OperationIds.AssetsCrop,
        OperationIds.AssetsReset,
        OperationIds.AssetsRemove,
        OperationIds.ProfilesList,
        OperationIds.ProfilesGet,
        OperationIds.ProfilesCreate,
        OperationIds.ProfilesUpdate,
        OperationIds.ProfilesRemove,
        OperationIds.ProfilesSetDefault,
        OperationIds.ProfilesValidate,
        OperationIds.TranslationGet,
        OperationIds.TranslationSet,
        OperationIds.ToolsDiscover,
        OperationIds.VerificationStart,
        OperationIds.VerificationGet,
        OperationIds.VerificationList,
        OperationIds.VerificationReport,
        OperationIds.VerificationInvalidate,
        OperationIds.LaunchPlan,
        OperationIds.LaunchExecute,
        OperationIds.LaunchStatus,
        OperationIds.LaunchHistory,
        OperationIds.JobsGet,
        OperationIds.JobsCancel,
        OperationIds.EventsRead,
        OperationIds.NotificationsList,
        OperationIds.NotificationsGet,
        OperationIds.NotificationsAcknowledge,
        OperationIds.NotificationsDefer,
        OperationIds.SettingsGet,
        OperationIds.SettingsUpdate,
        OperationIds.SettingsReset,
        OperationIds.ViewsList,
        OperationIds.ViewsGet,
        OperationIds.ViewsCreate,
        OperationIds.ViewsUpdate,
        OperationIds.ViewsRemove,
        OperationIds.ViewsActivate,
        OperationIds.BackupsList,
        OperationIds.BackupsCreate,
        OperationIds.BackupsInspect,
        OperationIds.BackupsRestorePlan,
        OperationIds.BackupsRestore,
        OperationIds.DiagnosticsStatus,
        OperationIds.DiagnosticsLogs,
        OperationIds.DiagnosticsCacheRebuild,
        OperationIds.EventsWait,
        OperationIds.BackupsRestoreStart,
        OperationIds.CandidatesReviewBatch,
        OperationIds.TagsReorder,
    };

    internal static readonly IReadOnlyDictionary<string, ParamSpec[]> InputSpecs =
        new Dictionary<string, ParamSpec[]>(StringComparer.Ordinal)
        {
            [OperationIds.ProfilesDiscover] = [new("gameId", "string", false, "游戏 ID；省略时回填库内游戏"), new("idempotencyKey", "string", true, "识别幂等键")],
            [OperationIds.TitlesTranslate] = [new("gameIds", "array", true, "gameIds"), new("engine", "string", false, "engine"), new("force", "boolean", false, "force"), new("idempotencyKey", "string", true, "idempotencyKey")],
            [OperationIds.TitlesSetDisplay] = [new("gameId", "string", true, "gameId"), new("mode", "string", true, "mode"), new("expectedRevision", "integer", true, "expectedRevision"), new("idempotencyKey", "string", true, "idempotencyKey")],
            [OperationIds.TitlesSetTranslated] = [new("gameId", "string", true, "gameId"), new("title", "string", true, "title"), new("expectedRevision", "integer", true, "expectedRevision"), new("idempotencyKey", "string", true, "idempotencyKey")],
            [OperationIds.ProfilesRestore] = [new("profileId", "string", true, "启动方式 ID"), new("expectedRevision", "integer", true, "预期修订号"), new("idempotencyKey", "string", true, "恢复幂等键")],
            [OperationIds.CapabilitiesGet] = [],
            [OperationIds.HostStatus] = [],
            [OperationIds.HostStop] = [new("idempotencyKey", "string", true, "停机幂等键")],
            [OperationIds.LibraryInit] = [new("idempotencyKey", "string", false, "建库幂等键；提供后登记收据")],
            [OperationIds.RootsList] = [new("includeManual", "boolean", false, "包含 manual 根（默认只返回 library 根；manual 根是手动添加游戏的包含边界）")],
            [OperationIds.RootsAdd] = [new("root", "string", true, "库根绝对路径"), new("kind", "string", false, "根类型 library/manual（默认 library；manual 仅作路径包含边界，不参与扫描枚举与候选发现）"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.RootsRemove] = [new("rootId", "string", true, "库根 ID"), new("expectedRevision", "integer", true, "期望库根修订"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.ScanStart] = [new("root", "string", true, "扫描根（须在已注册库根内）"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.ScanStatus] = [new("jobId", "string", true, "作业 ID")],
            [OperationIds.ScanCancel] = [new("jobId", "string", true, "作业 ID"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.ScanCoverage] = [new("jobId", "string", true, "作业 ID")],
            [OperationIds.ScanInspect] = [new("path", "string", true, "待识别目录（须在已注册库根内）")],
            [OperationIds.CandidatesList] = [new("jobId", "string", false, "按扫描作业 ID 过滤"), new("state", "string", false, "按审核状态过滤"), new("limit", "integer", false, "分页大小（1–1000）"), new("offset", "integer", false, "分页偏移")],
            [OperationIds.CandidatesGet] = [new("candidateId", "string", true, "候选 ID")],
            [OperationIds.CandidatesAccept] = [new("candidateId", "string", true, "候选 ID"), new("expectedRevision", "integer", true, "期望修订"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.CandidatesDefer] = [new("candidateId", "string", true, "候选 ID"), new("expectedRevision", "integer", true, "期望修订"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.CandidatesIgnore] = [new("candidateId", "string", true, "候选 ID"), new("expectedRevision", "integer", true, "期望修订"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.IgnoresList] = [],
            [OperationIds.IgnoresCreate] = [new("scope", "string", true, "ExactPath / Subtree / ConfirmedIdentity"), new("path", "string", false, "路径类规则的路径"), new("gameId", "string", false, "身份类规则的游戏 ID"), new("reason", "string", false, "原因"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.IgnoresRemove] = [new("ignoreId", "string", true, "忽略规则 ID"), new("expectedRevision", "integer", true, "期望修订"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.GamesList] = [new("search", "string", false, "搜索词（命中用户标题或原文件夹名，数据库侧执行）"), new("favorite", "boolean", false, "仅收藏"), new("sort", "string", false, "title/title-asc、title-desc、recent/updated-desc 或 accepted-desc"), new("viewId", "string", false, "套用视图筛选/排序"), new("tagId", "string", false, "按标签过滤（与搜索 AND 组合）"), new("limit", "integer", false, "分页大小（1–1000）"), new("offset", "integer", false, "分页偏移")],
            [OperationIds.GamesGet] = [new("gameId", "string", true, "游戏 ID")],
            [OperationIds.GamesCreate] = [new("sourcePath", "string", true, "已注册游戏库内的目录或独立 EXE/SWF/LNK 绝对路径"), new("title", "string", false, "卡片标题；省略时取文件或目录名"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.GamesUpdate] = [new("gameId", "string", true, "游戏 ID"), new("favorite", "boolean", false, "收藏标记"), new("expectedRevision", "integer", true, "期望修订"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.GamesRemove] = [new("deleteFiles", "boolean", false, "同时将原文件移入回收站，必须明确确认路径"), new("confirmedPath", "string", false, "删除原文件时确认的完整游戏路径"), new("gameId", "string", true, "游戏 ID"), new("expectedRevision", "integer", true, "期望修订"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.GamesRelink] = [new("gameId", "string", true, "游戏 ID"), new("newPath", "string", true, "新路径（仅改绑定，不移动文件）"), new("expectedRevision", "integer", true, "期望修订"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.FieldsSet] = [new("gameId", "string", true, "游戏 ID"), new("field", "string", true, "字段：title / summary"), new("value", "string", true, "字段值"), new("expectedRevision", "integer", true, "期望修订"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.FieldsClear] = [new("gameId", "string", true, "游戏 ID"), new("field", "string", true, "字段名"), new("expectedRevision", "integer", true, "期望修订"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.FieldsReset] = [new("gameId", "string", true, "游戏 ID"), new("field", "string", true, "字段名"), new("expectedRevision", "integer", true, "期望修订"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.TagsList] = [],
            [OperationIds.TagsCreate] = [new("name", "string", true, "标签名（1–100 字符）"), new("color", "string", false, "颜色 #RRGGBB（可选）"), new("category", "string", false, "分类 engine/gameplay/social/special（缺省按 kind 推断：user 标签为 special）"), new("sortOrder", "integer", false, "排序权重（缺省 0）"), new("starred", "integer", false, "星级评分 0–5（0=无评分，缺省 0）"), new("displayName", "string", false, "显示名（缺省同 name）"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.TagsUpdate] = [new("tagId", "string", true, "标签 ID"), new("name", "string", false, "新名称（可选；engine 标签 name 是身份键不可改，改名用 displayName）"), new("color", "string", false, "新颜色 #RRGGBB（可选，engine 标签同样允许）"), new("category", "string", false, "新分类 engine/gameplay/social/special（可选，engine 标签同样允许）"), new("sortOrder", "integer", false, "新排序权重（可选）"), new("starred", "integer", false, "新星级评分 0–5（可选，0=清除评分）"), new("displayName", "string", false, "新显示名（可选；传 null 清除，回落 name）"), new("expectedRevision", "integer", true, "期望标签修订"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.TagsRemove] = [new("tagId", "string", true, "标签 ID"), new("expectedRevision", "integer", true, "期望标签修订"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.TagsAssign] = [new("gameId", "string", true, "游戏 ID"), new("tagId", "string", true, "标签 ID"), new("expectedRevision", "integer", true, "期望游戏修订"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.TagsUnassign] = [new("gameId", "string", true, "游戏 ID"), new("tagId", "string", true, "标签 ID"), new("expectedRevision", "integer", true, "期望游戏修订"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.TagsSuppress] = [new("gameId", "string", true, "游戏 ID"), new("tagId", "string", true, "标签 ID"), new("expectedRevision", "integer", true, "期望游戏修订"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.TagsReset] = [new("gameId", "string", true, "游戏 ID"), new("tagId", "string", true, "标签 ID"), new("expectedRevision", "integer", true, "期望游戏修订"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.MetadataPreview] = [new("gameId", "string", true, "游戏 ID")],
            [OperationIds.MetadataRefresh] = [new("gameId", "string", true, "游戏 ID"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.AssetsList] = [new("gameId", "string", true, "游戏 ID")],
            [OperationIds.AssetsGet] = [new("assetId", "string", true, "资产 ID")],
            [OperationIds.AssetsImport] = [new("gameId", "string", true, "游戏 ID"), new("sourcePath", "string", true, "图片绝对路径（复制入应用目录）"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.AssetsChoose] = [new("gameId", "string", true, "游戏 ID"), new("assetId", "string", true, "资产 ID"), new("expectedRevision", "integer", true, "期望修订"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.AssetsCrop] = [new("gameId", "string", true, "游戏 ID"), new("assetId", "string", true, "资产 ID"), new("expectedRevision", "integer", true, "期望修订"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.AssetsReset] = [new("gameId", "string", true, "游戏 ID"), new("expectedRevision", "integer", true, "期望修订"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.AssetsRemove] = [new("assetId", "string", true, "资产 ID"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.ProfilesList] = [new("gameId", "string", false, "按游戏过滤")],
            [OperationIds.ProfilesGet] = [new("profileId", "string", true, "Profile ID")],
            [OperationIds.ProfilesCreate] = [new("gameId", "string", true, "游戏 ID"), new("executablePath", "string", true, "启动 EXE 或 SWF 的绝对路径"), new("argv", "array", true, "启动参数字符串数组"), new("cwd", "string", true, "工作目录"), new("isDefault", "boolean", false, "是否默认 Profile"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.ProfilesUpdate] = [new("profileId", "string", true, "Profile ID"), new("executablePath", "string", true, "新的 EXE 或 SWF 路径"), new("argv", "array", true, "新启动参数字符串数组"), new("cwd", "string", true, "新工作目录"), new("expectedRevision", "integer", true, "期望 Profile 修订"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.ProfilesRemove] = [new("profileId", "string", true, "Profile ID"), new("expectedRevision", "integer", true, "期望 Profile 修订"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.ProfilesSetDefault] = [new("gameId", "string", true, "游戏 ID"), new("profileId", "string", true, "Profile ID"), new("expectedRevision", "integer", true, "期望 Profile 修订"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.ProfilesValidate] = [new("profileId", "string", true, "Profile ID")],
            [OperationIds.TranslationGet] = [new("gameId", "string", true, "游戏 ID")],
            [OperationIds.TranslationSet] = [new("gameId", "string", true, "游戏 ID"), new("override", "string", true, "Auto / Required / NotRequired"), new("expectedRevision", "integer", true, "期望修订"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.ToolsDiscover] = [new("tool", "string", false, "mtool / renpythief / player / steam"), new("path", "string", false, "工具发现目标路径"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.VerificationStart] = [new("toolId", "string", true, "工具 ID"), new("samplePath", "string", true, "授权样本路径"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.VerificationGet] = [new("recordId", "string", true, "验证记录 ID")],
            [OperationIds.VerificationList] = [new("toolId", "string", false, "按工具过滤")],
            [OperationIds.VerificationReport] = [new("recordId", "string", true, "验证记录 ID"), new("gameStarted", "boolean", true, "游戏是否启动"), new("translationConfirmed", "boolean", true, "翻译是否确认"), new("note", "string", false, "备注")],
            [OperationIds.VerificationInvalidate] = [new("recordId", "string", true, "验证记录 ID"), new("expectedRevision", "integer", true, "期望修订"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.LaunchPlan] = [new("gameId", "string", true, "游戏 ID"), new("profileId", "string", true, "Profile ID")],
            [OperationIds.LaunchExecute] = [new("planId", "string", false, "预览计划 ID"), new("profileId", "string", false, "直接按 Profile 执行"), new("expectedRevision", "integer", false, "期望 Profile 修订"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.LaunchStatus] = [new("attemptId", "string", true, "尝试 ID")],
            [OperationIds.LaunchHistory] = [new("gameId", "string", false, "按游戏过滤")],
            [OperationIds.JobsGet] = [new("jobId", "string", true, "作业 ID")],
            [OperationIds.JobsCancel] = [new("jobId", "string", true, "jobId"), new("idempotencyKey", "string", true, "idempotencyKey")],
            [OperationIds.EventsRead] = [new("cursor", "integer", false, "游标（上次响应的 nextCursor）；缺省表示从头全量读取"), new("limit", "integer", false, "单批上限（1–4096）")],
            [OperationIds.NotificationsList] = [new("state", "string", false, "按状态过滤")],
            [OperationIds.NotificationsGet] = [new("notificationId", "string", true, "通知 ID")],
            [OperationIds.NotificationsAcknowledge] = [new("notificationId", "string", true, "通知 ID"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.NotificationsDefer] = [new("notificationId", "string", true, "通知 ID"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.SettingsGet] = [],
            [OperationIds.SettingsUpdate] = [new("titleTranslationEngine", "string", false, "titleTranslationEngine"), new("activeViewId", "string", false, "激活视图（字符串或 null）"), new("autostartEnabled", "boolean", false, "开机启动"), new("scanIntervalMinutes", "integer", false, "核对周期（1–10080 分钟）"), new("theme", "string", false, "dark / light / system"), new("closeToTray", "boolean", false, "关闭即缩托盘"), new("uiFontScale", "number", false, "界面缩放（0.85–1.6）"), new("uiLanguage", "string", false, "zh-CN / zh-TW / en / ja"), new("uiFontFamily", "string", false, "已安装字体的名称"), new("cacheParentDirectory", "string", false, "缓存存放位置的父目录；null 恢复默认"), new("expectedRevision", "integer", true, "期望设置修订"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.SettingsReset] = [new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.ViewsList] = [],
            [OperationIds.ViewsGet] = [new("viewId", "string", true, "视图 ID")],
            [OperationIds.ViewsCreate] = [new("name", "string", true, "视图名"), new("search", "string", false, "搜索词"), new("favoriteOnly", "boolean", false, "仅收藏"), new("tagId", "string", false, "按标签筛选"), new("sort", "string", false, "title/title-asc、title-desc、recent/updated-desc 或 accepted-desc"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.ViewsUpdate] = [new("viewId", "string", true, "视图 ID"), new("name", "string", false, "新名称"), new("search", "string", false, "新搜索词"), new("favoriteOnly", "boolean", false, "仅收藏"), new("tagId", "string", false, "按标签筛选"), new("sort", "string", false, "title/title-asc、title-desc、recent/updated-desc 或 accepted-desc"), new("expectedRevision", "integer", true, "期望修订"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.ViewsRemove] = [new("viewId", "string", true, "视图 ID"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.ViewsActivate] = [new("viewId", "string", true, "视图 ID"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.BackupsList] = [],
            [OperationIds.BackupsCreate] = [new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.BackupsInspect] = [new("backupId", "string", true, "备份 ID")],
            [OperationIds.BackupsRestorePlan] = [new("backupId", "string", true, "备份 ID")],
            [OperationIds.BackupsRestore] = [new("backupId", "string", true, "备份 ID"), new("planId", "string", true, "restore_plan 返回的计划 ID"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.DiagnosticsStatus] = [],
            [OperationIds.DiagnosticsLogs] = [new("limit", "integer", false, "最近记录条数（1–1000）")],
            [OperationIds.DiagnosticsCacheRebuild] = [new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.EventsWait] = [new("cursor", "integer", false, "增量游标"), new("limit", "integer", false, "批次上限"), new("timeoutMs", "integer", false, "等待毫秒，默认25000，最大30000")],
            [OperationIds.BackupsRestoreStart] = [new("backupId", "string", true, "备份 ID"), new("planId", "string", true, "restore_plan 返回的计划 ID"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.CandidatesReviewBatch] = [new("action", "string", true, "accept/defer/ignore"), new("items", "array", true, "最多1000个唯一ID与expectedRevision；标签项包含sortOrder"), new("idempotencyKey", "string", true, "幂等键")],
            [OperationIds.TagsReorder] = [new("items", "array", true, "最多1000个唯一ID与expectedRevision；标签项包含sortOrder"), new("idempotencyKey", "string", true, "幂等键")],
        };
}
