// <auto-generated />
#nullable enable
// Run: py -3 scripts/generate_operations.py
namespace GameLibrary.Contracts;

public static class OperationIds
{
    public const string ProfilesDiscover = "profiles.discover";
    public const string TitlesTranslate = "titles.translate";
    public const string TitlesSetDisplay = "titles.set_display";
    public const string TitlesSetTranslated = "titles.set_translated";
    public const string ProfilesRestore = "profiles.restore";
    public const string CapabilitiesGet = "capabilities.get";
    public const string SchemaGet = "schema.get";
    public const string HostStatus = "host.status";
    public const string HostStart = "host.start";
    public const string HostStop = "host.stop";
    public const string LibraryInit = "library.init";
    public const string LibraryStatus = "library.status";
    public const string LibraryExport = "library.export";
    public const string LibraryImportPlan = "library.import_plan";
    public const string LibraryImport = "library.import";
    public const string RootsList = "roots.list";
    public const string RootsGet = "roots.get";
    public const string RootsAdd = "roots.add";
    public const string RootsUpdate = "roots.update";
    public const string RootsRemove = "roots.remove";
    public const string RootsRebind = "roots.rebind";
    public const string RulesList = "rules.list";
    public const string RulesGet = "rules.get";
    public const string RulesCreate = "rules.create";
    public const string RulesUpdate = "rules.update";
    public const string RulesRemove = "rules.remove";
    public const string RulesPreview = "rules.preview";
    public const string ScanStart = "scan.start";
    public const string ScanStatus = "scan.status";
    public const string ScanPause = "scan.pause";
    public const string ScanResume = "scan.resume";
    public const string ScanCancel = "scan.cancel";
    public const string ScanCoverage = "scan.coverage";
    public const string ScanInspect = "scan.inspect";
    public const string CandidatesList = "candidates.list";
    public const string CandidatesGet = "candidates.get";
    public const string CandidatesInspect = "candidates.inspect";
    public const string CandidatesAccept = "candidates.accept";
    public const string CandidatesDefer = "candidates.defer";
    public const string CandidatesIgnore = "candidates.ignore";
    public const string IgnoresList = "ignores.list";
    public const string IgnoresGet = "ignores.get";
    public const string IgnoresCreate = "ignores.create";
    public const string IgnoresUpdate = "ignores.update";
    public const string IgnoresRemove = "ignores.remove";
    public const string GamesList = "games.list";
    public const string GamesGet = "games.get";
    public const string GamesCreate = "games.create";
    public const string GamesUpdate = "games.update";
    public const string GamesRemove = "games.remove";
    public const string GamesRelink = "games.relink";
    public const string FieldsSet = "fields.set";
    public const string FieldsClear = "fields.clear";
    public const string FieldsReset = "fields.reset";
    public const string TagsList = "tags.list";
    public const string TagsCreate = "tags.create";
    public const string TagsUpdate = "tags.update";
    public const string TagsRemove = "tags.remove";
    public const string TagsAssign = "tags.assign";
    public const string TagsUnassign = "tags.unassign";
    public const string TagsSuppress = "tags.suppress";
    public const string TagsReset = "tags.reset";
    public const string MetadataPreview = "metadata.preview";
    public const string MetadataRefresh = "metadata.refresh";
    public const string AssetsList = "assets.list";
    public const string AssetsGet = "assets.get";
    public const string AssetsImport = "assets.import";
    public const string AssetsChoose = "assets.choose";
    public const string AssetsCrop = "assets.crop";
    public const string AssetsReset = "assets.reset";
    public const string AssetsRemove = "assets.remove";
    public const string ProfilesList = "profiles.list";
    public const string ProfilesGet = "profiles.get";
    public const string ProfilesCreate = "profiles.create";
    public const string ProfilesUpdate = "profiles.update";
    public const string ProfilesRemove = "profiles.remove";
    public const string ProfilesSetDefault = "profiles.set_default";
    public const string ProfilesValidate = "profiles.validate";
    public const string TranslationGet = "translation.get";
    public const string TranslationSet = "translation.set";
    public const string ToolsList = "tools.list";
    public const string ToolsGet = "tools.get";
    public const string ToolsDiscover = "tools.discover";
    public const string ToolsRegister = "tools.register";
    public const string ToolsUpdate = "tools.update";
    public const string ToolsRemove = "tools.remove";
    public const string ToolsCapabilities = "tools.capabilities";
    public const string VerificationStart = "verification.start";
    public const string VerificationGet = "verification.get";
    public const string VerificationList = "verification.list";
    public const string VerificationReport = "verification.report";
    public const string VerificationInvalidate = "verification.invalidate";
    public const string LaunchPlan = "launch.plan";
    public const string LaunchExecute = "launch.execute";
    public const string LaunchStatus = "launch.status";
    public const string LaunchHistory = "launch.history";
    public const string JobsList = "jobs.list";
    public const string JobsGet = "jobs.get";
    public const string JobsWait = "jobs.wait";
    public const string JobsCancel = "jobs.cancel";
    public const string EventsRead = "events.read";
    public const string NotificationsList = "notifications.list";
    public const string NotificationsGet = "notifications.get";
    public const string NotificationsAcknowledge = "notifications.acknowledge";
    public const string NotificationsDefer = "notifications.defer";
    public const string SettingsGet = "settings.get";
    public const string UnityTranslationSettingsGet = "unity_translation.settings.get";
    public const string UnityTranslationSettingsSet = "unity_translation.settings.set";
    public const string UnityTranslationSettingsImport = "unity_translation.settings.import";
    public const string UnityTranslationStatus = "unity_translation.status";
    public const string UnityTranslationPending = "unity_translation.pending";
    public const string UnityTranslationConfigure = "unity_translation.configure";
    public const string UnityTranslationConfirm = "unity_translation.confirm";
    public const string UnityTranslationRestore = "unity_translation.restore";
    public const string SettingsUpdate = "settings.update";
    public const string SettingsReset = "settings.reset";
    public const string ViewsList = "views.list";
    public const string ViewsGet = "views.get";
    public const string ViewsCreate = "views.create";
    public const string ViewsUpdate = "views.update";
    public const string ViewsRemove = "views.remove";
    public const string ViewsActivate = "views.activate";
    public const string DesktopState = "desktop.state";
    public const string DesktopShow = "desktop.show";
    public const string DesktopNavigate = "desktop.navigate";
    public const string DesktopHide = "desktop.hide";
    public const string DesktopClose = "desktop.close";
    public const string BackupsList = "backups.list";
    public const string BackupsCreate = "backups.create";
    public const string BackupsInspect = "backups.inspect";
    public const string BackupsRestorePlan = "backups.restore_plan";
    public const string BackupsRestore = "backups.restore";
    public const string DiagnosticsStatus = "diagnostics.status";
    public const string DiagnosticsLogs = "diagnostics.logs";
    public const string DiagnosticsExport = "diagnostics.export";
    public const string DiagnosticsCacheRebuild = "diagnostics.cache_rebuild";
    public const string AccessStatus = "access.status";
    public const string AccessList = "access.list";
    public const string AccessConfigure = "access.configure";
    public const string AccessRevoke = "access.revoke";
    public const string ActionsList = "actions.list";
    public const string ActionsGet = "actions.get";
    public const string ActionsComplete = "actions.complete";
    public const string EventsWait = "events.wait";
    public const string BackupsRestoreStart = "backups.restore_start";
    public const string CandidatesReviewBatch = "candidates.review_batch";
    public const string TagsReorder = "tags.reorder";
}

internal static class GeneratedOperations
{
    internal static readonly IReadOnlySet<string> Available = new HashSet<string>(StringComparer.Ordinal)
    {
        OperationIds.ProfilesDiscover,
        OperationIds.TitlesTranslate,
        OperationIds.TitlesSetDisplay,
        OperationIds.TitlesSetTranslated,
        OperationIds.ProfilesRestore,
        OperationIds.CapabilitiesGet,
        OperationIds.SchemaGet,
        OperationIds.HostStatus,
        OperationIds.HostStop,
        OperationIds.LibraryInit,
        OperationIds.RootsList,
        OperationIds.RootsAdd,
        OperationIds.RootsRemove,
        OperationIds.ScanStart,
        OperationIds.ScanStatus,
        OperationIds.ScanCancel,
        OperationIds.ScanCoverage,
        OperationIds.ScanInspect,
        OperationIds.CandidatesList,
        OperationIds.CandidatesGet,
        OperationIds.CandidatesInspect,
        OperationIds.CandidatesAccept,
        OperationIds.CandidatesDefer,
        OperationIds.CandidatesIgnore,
        OperationIds.IgnoresList,
        OperationIds.IgnoresCreate,
        OperationIds.IgnoresRemove,
        OperationIds.GamesList,
        OperationIds.GamesGet,
        OperationIds.GamesCreate,
        OperationIds.GamesUpdate,
        OperationIds.GamesRemove,
        OperationIds.GamesRelink,
        OperationIds.FieldsSet,
        OperationIds.FieldsClear,
        OperationIds.FieldsReset,
        OperationIds.TagsList,
        OperationIds.TagsCreate,
        OperationIds.TagsUpdate,
        OperationIds.TagsRemove,
        OperationIds.TagsAssign,
        OperationIds.TagsUnassign,
        OperationIds.TagsSuppress,
        OperationIds.TagsReset,
        OperationIds.MetadataPreview,
        OperationIds.MetadataRefresh,
        OperationIds.AssetsList,
        OperationIds.AssetsGet,
        OperationIds.AssetsImport,
        OperationIds.AssetsChoose,
        OperationIds.AssetsCrop,
        OperationIds.AssetsReset,
        OperationIds.AssetsRemove,
        OperationIds.ProfilesList,
        OperationIds.ProfilesGet,
        OperationIds.ProfilesCreate,
        OperationIds.ProfilesUpdate,
        OperationIds.ProfilesRemove,
        OperationIds.ProfilesSetDefault,
        OperationIds.ProfilesValidate,
        OperationIds.TranslationGet,
        OperationIds.TranslationSet,
        OperationIds.ToolsDiscover,
        OperationIds.VerificationStart,
        OperationIds.VerificationGet,
        OperationIds.VerificationList,
        OperationIds.VerificationReport,
        OperationIds.VerificationInvalidate,
        OperationIds.LaunchPlan,
        OperationIds.LaunchExecute,
        OperationIds.LaunchStatus,
        OperationIds.LaunchHistory,
        OperationIds.JobsGet,
        OperationIds.JobsCancel,
        OperationIds.EventsRead,
        OperationIds.NotificationsList,
        OperationIds.NotificationsGet,
        OperationIds.NotificationsAcknowledge,
        OperationIds.NotificationsDefer,
        OperationIds.SettingsGet,
        OperationIds.UnityTranslationSettingsGet,
        OperationIds.UnityTranslationSettingsSet,
        OperationIds.UnityTranslationSettingsImport,
        OperationIds.UnityTranslationStatus,
        OperationIds.UnityTranslationPending,
        OperationIds.UnityTranslationConfigure,
        OperationIds.UnityTranslationConfirm,
        OperationIds.UnityTranslationRestore,
        OperationIds.SettingsUpdate,
        OperationIds.SettingsReset,
        OperationIds.ViewsList,
        OperationIds.ViewsGet,
        OperationIds.ViewsCreate,
        OperationIds.ViewsUpdate,
        OperationIds.ViewsRemove,
        OperationIds.ViewsActivate,
        OperationIds.BackupsList,
        OperationIds.BackupsCreate,
        OperationIds.BackupsInspect,
        OperationIds.BackupsRestorePlan,
        OperationIds.BackupsRestore,
        OperationIds.DiagnosticsStatus,
        OperationIds.DiagnosticsLogs,
        OperationIds.DiagnosticsCacheRebuild,
        OperationIds.EventsWait,
        OperationIds.BackupsRestoreStart,
        OperationIds.CandidatesReviewBatch,
        OperationIds.TagsReorder,
    };

    internal static readonly IReadOnlyDictionary<string, ParamSpec[]> InputSpecs =
        new Dictionary<string, ParamSpec[]>(StringComparer.Ordinal)
        {
            [OperationIds.ProfilesDiscover] = [new("gameId", "string", false, "游戏 ID；省略时回填库内游戏", false), new("idempotencyKey", "string", true, "识别幂等键", false)],
            [OperationIds.TitlesTranslate] = [new("gameIds", "array", true, "gameIds", false), new("engine", "string", false, "engine", false), new("force", "boolean", false, "force", false), new("idempotencyKey", "string", true, "idempotencyKey", false)],
            [OperationIds.TitlesSetDisplay] = [new("gameId", "string", true, "gameId", false), new("mode", "string", true, "mode", false), new("expectedRevision", "integer", true, "expectedRevision", false), new("idempotencyKey", "string", true, "idempotencyKey", false)],
            [OperationIds.TitlesSetTranslated] = [new("gameId", "string", true, "gameId", false), new("title", "string", true, "title", false), new("expectedRevision", "integer", true, "expectedRevision", false), new("idempotencyKey", "string", true, "idempotencyKey", false)],
            [OperationIds.ProfilesRestore] = [new("profileId", "string", true, "启动方式 ID", false), new("expectedRevision", "integer", true, "预期修订号", false), new("idempotencyKey", "string", true, "恢复幂等键", false)],
            [OperationIds.CapabilitiesGet] = [],
            [OperationIds.HostStatus] = [],
            [OperationIds.HostStop] = [new("idempotencyKey", "string", true, "停机幂等键", false)],
            [OperationIds.LibraryInit] = [new("idempotencyKey", "string", false, "建库幂等键；提供后登记收据", false)],
            [OperationIds.RootsList] = [new("includeManual", "boolean", false, "包含 manual 根（默认只返回 library 根；manual 根是手动添加游戏的包含边界）", false)],
            [OperationIds.RootsAdd] = [new("root", "string", true, "库根绝对路径", false), new("kind", "string", false, "根类型 library/manual（默认 library；manual 仅作路径包含边界，不参与扫描枚举与候选发现）", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.RootsRemove] = [new("rootId", "string", true, "库根 ID", false), new("expectedRevision", "integer", true, "期望库根修订", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.ScanStart] = [new("root", "string", true, "扫描根（须在已注册库根内）", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.ScanStatus] = [new("jobId", "string", true, "作业 ID", false)],
            [OperationIds.ScanCancel] = [new("jobId", "string", true, "作业 ID", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.ScanCoverage] = [new("jobId", "string", true, "作业 ID", false)],
            [OperationIds.ScanInspect] = [new("path", "string", true, "待识别目录（须在已注册库根内）", false)],
            [OperationIds.CandidatesList] = [new("jobId", "string", false, "按扫描作业 ID 过滤", false), new("state", "string", false, "按审核状态过滤", false), new("limit", "integer", false, "分页大小（1–1000）", false), new("offset", "integer", false, "分页偏移", false)],
            [OperationIds.CandidatesGet] = [new("candidateId", "string", true, "候选 ID", false)],
            [OperationIds.CandidatesInspect] = [new("candidateId", "string", true, "候选 ID", false), new("flashKind", "string", false, "预览 Flash project/collection/resources 判断", false), new("entryPaths", "array", false, "预览所选游戏入口", false)],
            [OperationIds.CandidatesAccept] = [new("candidateId", "string", true, "候选 ID", false), new("expectedRevision", "integer", true, "期望修订", false), new("idempotencyKey", "string", true, "幂等键", false), new("flashKind", "string", false, "Flash 目录判断 project/collection/resources", false), new("entryPaths", "array", false, "所选完整游戏入口", false), new("adjustments", "array", false, "inspect 返回的整份已有游戏调整清单，包含 gameId 和 expectedRevision", false)],
            [OperationIds.CandidatesDefer] = [new("candidateId", "string", true, "候选 ID", false), new("expectedRevision", "integer", true, "期望修订", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.CandidatesIgnore] = [new("candidateId", "string", true, "候选 ID", false), new("expectedRevision", "integer", true, "期望修订", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.IgnoresList] = [],
            [OperationIds.IgnoresCreate] = [new("scope", "string", true, "ExactPath / Subtree / ConfirmedIdentity", false), new("path", "string", false, "路径类规则的路径", false), new("gameId", "string", false, "身份类规则的游戏 ID", false), new("reason", "string", false, "原因", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.IgnoresRemove] = [new("ignoreId", "string", true, "忽略规则 ID", false), new("expectedRevision", "integer", true, "期望修订", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.GamesList] = [new("search", "string", false, "搜索词（命中用户标题或原文件夹名，数据库侧执行）", false), new("favorite", "boolean", false, "仅收藏", false), new("sort", "string", false, "title/title-asc、title-desc、recent/updated-desc 或 accepted-desc", false), new("viewId", "string", false, "套用视图筛选/排序", false), new("tagId", "string", false, "按标签过滤（与搜索 AND 组合）", false), new("limit", "integer", false, "分页大小（1–1000）", false), new("offset", "integer", false, "分页偏移", false)],
            [OperationIds.GamesGet] = [new("gameId", "string", true, "游戏 ID", false)],
            [OperationIds.GamesCreate] = [new("sourcePath", "string", true, "已注册游戏库内的目录或独立 EXE/SWF/LNK 绝对路径", false), new("title", "string", false, "卡片标题；省略时取文件或目录名", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.GamesUpdate] = [new("gameId", "string", true, "游戏 ID", false), new("favorite", "boolean", false, "收藏标记", false), new("expectedRevision", "integer", true, "期望修订", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.GamesRemove] = [new("deleteFiles", "boolean", false, "同时将原文件移入回收站，必须明确确认路径", false), new("confirmedPath", "string", false, "删除原文件时确认的完整游戏路径", false), new("gameId", "string", true, "游戏 ID", false), new("expectedRevision", "integer", true, "期望修订", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.GamesRelink] = [new("gameId", "string", true, "游戏 ID", false), new("newPath", "string", true, "新路径（仅改绑定，不移动文件）", false), new("expectedRevision", "integer", true, "期望修订", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.FieldsSet] = [new("gameId", "string", true, "游戏 ID", false), new("field", "string", true, "字段：title / summary", false), new("value", "string", true, "字段值", false), new("expectedRevision", "integer", true, "期望修订", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.FieldsClear] = [new("gameId", "string", true, "游戏 ID", false), new("field", "string", true, "字段名", false), new("expectedRevision", "integer", true, "期望修订", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.FieldsReset] = [new("gameId", "string", true, "游戏 ID", false), new("field", "string", true, "字段名", false), new("expectedRevision", "integer", true, "期望修订", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.TagsList] = [],
            [OperationIds.TagsCreate] = [new("name", "string", true, "标签名（1–100 字符）", false), new("color", "string", false, "颜色 #RRGGBB（可选）", false), new("category", "string", false, "分类 engine/gameplay/social/special（缺省按 kind 推断：user 标签为 special）", false), new("sortOrder", "integer", false, "排序权重（缺省 0）", false), new("starred", "integer", false, "星级评分 0–5（0=无评分，缺省 0）", false), new("displayName", "string", false, "显示名（缺省同 name）", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.TagsUpdate] = [new("tagId", "string", true, "标签 ID", false), new("name", "string", false, "新名称（可选；engine 标签 name 是身份键不可改，改名用 displayName）", false), new("color", "string", false, "颜色 #RRGGBB；显式 null 清除为主题默认色，省略保持原值", true), new("category", "string", false, "新分类 engine/gameplay/social/special（可选，engine 标签同样允许）", false), new("sortOrder", "integer", false, "新排序权重（可选）", false), new("starred", "integer", false, "新星级评分 0–5（可选，0=清除评分）", false), new("displayName", "string", false, "新显示名（可选；传 null 清除，回落 name）", true), new("expectedRevision", "integer", true, "期望标签修订", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.TagsRemove] = [new("tagId", "string", true, "标签 ID", false), new("expectedRevision", "integer", true, "期望标签修订", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.TagsAssign] = [new("gameId", "string", true, "游戏 ID", false), new("tagId", "string", true, "标签 ID", false), new("expectedRevision", "integer", true, "期望游戏修订", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.TagsUnassign] = [new("gameId", "string", true, "游戏 ID", false), new("tagId", "string", true, "标签 ID", false), new("expectedRevision", "integer", true, "期望游戏修订", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.TagsSuppress] = [new("gameId", "string", true, "游戏 ID", false), new("tagId", "string", true, "标签 ID", false), new("expectedRevision", "integer", true, "期望游戏修订", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.TagsReset] = [new("gameId", "string", true, "游戏 ID", false), new("tagId", "string", true, "标签 ID", false), new("expectedRevision", "integer", true, "期望游戏修订", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.MetadataPreview] = [new("gameId", "string", true, "游戏 ID", false)],
            [OperationIds.MetadataRefresh] = [new("gameId", "string", true, "游戏 ID", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.AssetsList] = [new("gameId", "string", true, "游戏 ID", false)],
            [OperationIds.AssetsGet] = [new("assetId", "string", true, "资产 ID", false)],
            [OperationIds.AssetsImport] = [new("gameId", "string", true, "游戏 ID", false), new("sourcePath", "string", false, "图片绝对路径（复制入应用目录）", false), new("imageBase64", "string", false, "图片 Base64，解码后最多 5 MiB；与 sourcePath 二选一", false), new("mimeType", "string", false, "剪贴板图片 MIME 类型", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.AssetsChoose] = [new("gameId", "string", true, "游戏 ID", false), new("assetId", "string", true, "资产 ID", false), new("expectedRevision", "integer", true, "期望修订", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.AssetsCrop] = [new("gameId", "string", true, "游戏 ID", false), new("assetId", "string", true, "资产 ID", false), new("x", "integer", true, "裁切起点 X", false), new("y", "integer", true, "裁切起点 Y", false), new("width", "integer", true, "裁切宽度", false), new("height", "integer", true, "裁切高度", false), new("expectedRevision", "integer", true, "期望修订", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.AssetsReset] = [new("gameId", "string", true, "游戏 ID", false), new("expectedRevision", "integer", true, "期望修订", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.AssetsRemove] = [new("assetId", "string", true, "资产 ID", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.ProfilesList] = [new("gameId", "string", false, "按游戏过滤", false)],
            [OperationIds.ProfilesGet] = [new("profileId", "string", true, "Profile ID", false)],
            [OperationIds.ProfilesCreate] = [new("gameId", "string", true, "游戏 ID", false), new("executablePath", "string", true, "启动 EXE 或 SWF 的绝对路径", false), new("argv", "array", true, "启动参数字符串数组", false), new("cwd", "string", true, "工作目录", false), new("isDefault", "boolean", false, "是否默认 Profile", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.ProfilesUpdate] = [new("profileId", "string", true, "Profile ID", false), new("executablePath", "string", true, "新的 EXE 或 SWF 路径", false), new("argv", "array", true, "新启动参数字符串数组", false), new("cwd", "string", true, "新工作目录", false), new("expectedRevision", "integer", true, "期望 Profile 修订", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.ProfilesRemove] = [new("profileId", "string", true, "Profile ID", false), new("expectedRevision", "integer", true, "期望 Profile 修订", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.ProfilesSetDefault] = [new("gameId", "string", true, "游戏 ID", false), new("profileId", "string", true, "Profile ID", false), new("expectedRevision", "integer", true, "期望 Profile 修订", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.ProfilesValidate] = [new("profileId", "string", true, "Profile ID", false)],
            [OperationIds.TranslationGet] = [new("gameId", "string", true, "游戏 ID", false)],
            [OperationIds.TranslationSet] = [new("gameId", "string", true, "游戏 ID", false), new("override", "string", true, "Auto / Required / NotRequired", false), new("expectedRevision", "integer", true, "期望修订", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.ToolsDiscover] = [new("tool", "string", false, "mtool / renpythief / player / steam", false), new("path", "string", false, "工具发现目标路径", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.VerificationStart] = [new("toolId", "string", true, "工具 ID", false), new("samplePath", "string", true, "授权样本路径", false), new("fingerprint", "string", true, "工具指纹", false), new("engine", "string", true, "样本游戏引擎标识", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.VerificationGet] = [new("recordId", "string", true, "验证记录 ID", false)],
            [OperationIds.VerificationList] = [new("toolId", "string", false, "按工具过滤", false)],
            [OperationIds.VerificationReport] = [new("recordId", "string", true, "验证记录 ID", false), new("gameStarted", "boolean", true, "游戏是否启动", false), new("translationConfirmed", "boolean", true, "翻译是否确认", false), new("note", "string", false, "备注", false), new("fingerprint", "string", false, "工具指纹（可选校验）", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.VerificationInvalidate] = [new("recordId", "string", true, "验证记录 ID", false), new("expectedRevision", "integer", true, "期望修订", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.LaunchPlan] = [new("gameId", "string", true, "游戏 ID", false), new("profileId", "string", true, "Profile ID", false)],
            [OperationIds.LaunchExecute] = [new("planId", "string", false, "预览计划 ID", false), new("profileId", "string", false, "直接按 Profile 执行", false), new("expectedRevision", "integer", false, "期望 Profile 修订", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.LaunchStatus] = [new("attemptId", "string", true, "尝试 ID", false)],
            [OperationIds.LaunchHistory] = [new("gameId", "string", false, "按游戏过滤", false)],
            [OperationIds.JobsGet] = [new("jobId", "string", true, "作业 ID", false)],
            [OperationIds.JobsCancel] = [new("jobId", "string", true, "jobId", false), new("idempotencyKey", "string", true, "idempotencyKey", false)],
            [OperationIds.EventsRead] = [new("cursor", "integer", false, "游标（上次响应的 nextCursor）；缺省表示从头全量读取", false), new("limit", "integer", false, "单批上限（1–4096）", false)],
            [OperationIds.NotificationsList] = [new("state", "string", false, "按状态过滤", false)],
            [OperationIds.NotificationsGet] = [new("notificationId", "string", true, "通知 ID", false)],
            [OperationIds.NotificationsAcknowledge] = [new("notificationId", "string", true, "通知 ID", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.NotificationsDefer] = [new("notificationId", "string", true, "通知 ID", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.SettingsGet] = [],
            [OperationIds.UnityTranslationSettingsGet] = [],
            [OperationIds.UnityTranslationSettingsSet] = [new("provider", "string", false, "deepseek 或 openai", false), new("endpoint", "string", false, "HTTPS 服务地址；本机允许 HTTP", false), new("model", "string", false, "模型名称", false), new("apiKey", "string", false, "本机密钥；省略保留同供应商和同来源的已保存密钥", false), new("boundTagId", "string", false, "触发自动配置的用户标签 ID", false), new("enabled", "boolean", false, "启用自动配置", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.UnityTranslationSettingsImport] = [new("configPath", "string", false, "本机 Config.ini；省略时尝试发现已有 Unity 配置", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.UnityTranslationStatus] = [new("gameId", "string", false, "仅查询该游戏", false)],
            [OperationIds.UnityTranslationPending] = [new("gameId", "string", false, "仅查询该游戏", false)],
            [OperationIds.UnityTranslationConfigure] = [new("gameIds", "array", true, "1–1000 个唯一游戏 ID；实际入口必须为 Unity Mono 且带绑定标签", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.UnityTranslationConfirm] = [new("gameId", "string", true, "游戏 ID", false), new("attemptId", "string", true, "当前配置尝试 ID", false), new("success", "boolean", true, "用户实际运行后是否确认成功；false 保留配置和标签", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.UnityTranslationRestore] = [new("gameId", "string", true, "恢复该游戏的本机原始备份", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.SettingsUpdate] = [new("titleTranslationEngine", "string", false, "titleTranslationEngine", false), new("activeViewId", "string", false, "激活视图（字符串或 null）", false), new("autostartEnabled", "boolean", false, "开机启动", false), new("scanIntervalMinutes", "integer", false, "核对周期（1–10080 分钟）", false), new("theme", "string", false, "dark / light / system", false), new("closeToTray", "boolean", false, "关闭即缩托盘", false), new("uiFontScale", "number", false, "界面缩放（0.85–1.6）", false), new("uiLanguage", "string", false, "zh-CN / zh-TW / en / ja", false), new("uiFontFamily", "string", false, "已安装字体的名称", false), new("cacheParentDirectory", "string", false, "缓存存放位置的父目录；null 恢复默认", false), new("expectedRevision", "integer", true, "期望设置修订", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.SettingsReset] = [new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.ViewsList] = [],
            [OperationIds.ViewsGet] = [new("viewId", "string", true, "视图 ID", false)],
            [OperationIds.ViewsCreate] = [new("name", "string", true, "视图名", false), new("search", "string", false, "搜索词", false), new("favoriteOnly", "boolean", false, "仅收藏", false), new("tagId", "string", false, "按标签筛选", false), new("sort", "string", false, "title/title-asc、title-desc、recent/updated-desc 或 accepted-desc", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.ViewsUpdate] = [new("viewId", "string", true, "视图 ID", false), new("name", "string", false, "新名称", false), new("search", "string", false, "新搜索词", false), new("favoriteOnly", "boolean", false, "仅收藏", false), new("tagId", "string", false, "按标签筛选", false), new("sort", "string", false, "title/title-asc、title-desc、recent/updated-desc 或 accepted-desc", false), new("expectedRevision", "integer", true, "期望修订", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.ViewsRemove] = [new("viewId", "string", true, "视图 ID", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.ViewsActivate] = [new("viewId", "string", true, "视图 ID", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.BackupsList] = [],
            [OperationIds.BackupsCreate] = [new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.BackupsInspect] = [new("backupId", "string", true, "备份 ID", false)],
            [OperationIds.BackupsRestorePlan] = [new("backupId", "string", true, "备份 ID", false)],
            [OperationIds.BackupsRestore] = [new("backupId", "string", true, "备份 ID", false), new("planId", "string", true, "restore_plan 返回的计划 ID", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.DiagnosticsStatus] = [],
            [OperationIds.DiagnosticsLogs] = [new("limit", "integer", false, "最近记录条数（1–1000）", false)],
            [OperationIds.DiagnosticsCacheRebuild] = [new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.EventsWait] = [new("cursor", "integer", false, "增量游标", false), new("limit", "integer", false, "批次上限", false), new("timeoutMs", "integer", false, "等待毫秒，默认25000，最大30000", false)],
            [OperationIds.BackupsRestoreStart] = [new("backupId", "string", true, "备份 ID", false), new("planId", "string", true, "restore_plan 返回的计划 ID", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.CandidatesReviewBatch] = [new("action", "string", true, "accept/defer/ignore", false), new("items", "array", true, "最多1000个candidateId/expectedRevision；Flash项可包含flashKind、entryPaths和确认的adjustments", false), new("idempotencyKey", "string", true, "幂等键", false)],
            [OperationIds.TagsReorder] = [new("items", "array", true, "最多1000个唯一ID与expectedRevision；标签项包含sortOrder", false), new("idempotencyKey", "string", true, "幂等键", false)],
        };
}
